# Generated by Django 5.2.6 on 2025-09-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="campus.professor",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="rosters", to="campus.student"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "name"],
                "unique_together": {("professor", "name")},
            },
        ),
    ]
