# Generated by Django 5.2.6 on 2025-09-30 00:57

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0002_roster"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("professor", "email")},
        ),
        migrations.AddField(
            model_name="roster",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="roster",
            name="invoice_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RemoveField(
            model_name="student",
            name="major",
        ),
    ]
